const suggestions = [
  "e.g. Pretend I know what I’m doing",
  "e.g. Become one with the couch",
  "e.g. Drink coffee like it’s water",
  "e.g. Stare into the abyss of my to-do list",
  "e.g. Cancel plans and call it self-care",
  "e.g. Check fridge for food...find nothing, cry",
  "e.g. Google 'how to be a functioning adult'",
  "e.g. Find a reason to leave the house, but never do",
  "e.g. Check if bed is still comfy—spoiler: it is",
  "e.g. Set alarm for 7am, wake up at 11am",
  "e.g. Wonder why I’m still in pajamas at 3pm",
  "e.g. Avoid all responsibilities like a pro",
  "e.g. Open the fridge, close the fridge, repeat",
  "e.g. Pretend to be busy while secretly scrolling",
  "e.g. Remember to pretend I'm busy",
  "e.g. Remember to check if the Wi-Fi is working (again)",
  "e.g. Remember to avoid adult responsibilities",
  "e.g. Remember to drink water... after the coffee",
  "e.g. Remember to act like I have my life together",
  "e.g. Remember to text back… in 3-5 business days",
  "e.g. Remember to find the remote... under the blanket",
  "e.g. Remember to reply to emails with a single emoji",
  "e.g. Remember to procrastinate with purpose",
  "e.g. Remember to wear pants… maybe",
  "e.g. Remember to check my phone... then forget why",
  "e.g. Remember to make a to-do list and ignore it",
  "e.g. Remember to check if the plants are still alive, again",
  "e.g. Remember to take a 3-hour `quick` break",
  "e.g. Remember to make plans, then cancel them",
  "e.g. Remember to buy groceries, then eat cereal for dinner",
  "e.g. Remember to reorganize the chaos in my mind",
  "e.g. Remember to take the dog for a walk... but first, nap",
  "e.g. Remember to check social media like it’s a job",
  "e.g. Remember to check my email... and ignore it",
  "e.g. Remember to answer the door, but forget why",
  "e.g. Remember to act like I’m an adult... in public",
  "e.g. Remember to pretend to enjoy meetings",
  "e.g. Ask the fridge what’s for dinner, get no response",
  "e.g. Master the art of looking like I’m listening",
  "e.g. Make a to-do list and immediately ignore it",
  "e.g. Pretend my laundry pile doesn’t exist",
  "e.g. Wonder why I’m still scrolling through memes at 2 AM",
  "e.g. Take a break, then immediately need another break",
  "e.g. Try to read a book, end up reading the same page 5 times",
  "e.g. Stare at the calendar, then forget what day it is",
  "e.g. Lose track of time while watching random YouTube videos",
  "e.g. Overthink simple decisions for at least 20 minutes",
  "e.g. Take a shower... or just reapply deodorant",
];

export function getFunnySuggestion(): string {
  const randomIndex = Math.floor(Math.random() * suggestions.length);
  return suggestions[randomIndex];
}
